FROM ruby:2.3.1

ADD ./ /src
WORKDIR /src
RUN gem install bundler
RUN bundle install
ENTRYPOINT ["bundle","exec"]
CMD ["./subscription_manager.rb", "-p", "80", "-o", "0.0.0.0"]

VOLUME /var/run/docker.sock
EXPOSE 80

ENV DOCKER_IMAGE_NAME rranshous/chatbridge_sender
