FROM ruby:2.2.3

ADD ./ /src
WORKDIR /src
RUN gem install bundler
RUN bundle install --system
ENTRYPOINT ["bundle", "exec"]
CMD ["./sender.rb"]

VOLUME /data

ENV HIPCHAT_ROOM_NAME test
ENV API_KEY setme
ENV HIPCHAT_SENDER bot
ENV MESSAGE_TARGET setme
ENV STATE_DATA_DIR /data
